version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: upbase
    environment:
      MYSQL_ROOT_PASSWORD: prisma
      MYSQL_DATABASE: prisma
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

#version: '3'
#
#services:
#  api-solid-pg:
#    image: bitnami/postgresql
#    ports:
#      - 5432:5432
#    environment:
#      - POSTGRESQL_USERNAME=docker
#      - POSTGRESQL_PASSWORD=docker
#      - POSTGRESQL_DATABASE=upbase
